[package]
name = "voxelified/flake"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
rodux = "roblox/rodux@4.0.0-rc.0"
llama = "freddylist/llama@1.1.1"
roact-compat = "core-packages/roact-compat@17.0.1-rc.16.1"